package com.example.ui

import android.app.Application
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.data.*
import java.io.File
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.io.InputStream
import java.text.SimpleDateFormat
import java.util.*

class DiaryViewModel(application: Application) : AndroidViewModel(application) {

    private val database = DiaryDatabase.getDatabase(application)
    private val repository = DiaryRepository(database.diaryDao())

    // --- Authentication & Session Storage ---
    private val sharedPrefs = application.getSharedPreferences("diary_settings", Context.MODE_PRIVATE)
    
    var isPasswordSet by mutableStateOf(sharedPrefs.contains("password_hash"))
        private set

    var isDecoyPasswordSet by mutableStateOf(sharedPrefs.contains("fake_password_hash"))
        private set
    
    var isUnlocked by mutableStateOf(false)
        private set

    var masterPassword by mutableStateOf("")
        private set

    var isFakeVaultActive by mutableStateOf(false)
        private set

    var isRecoveryAuthSuccess by mutableStateOf(false)
        set
    var tempDecryptedMasterKey by mutableStateOf<String?>(null)
        set

    var localPrivacyOnly by mutableStateOf(sharedPrefs.getBoolean("local_privacy_only", false))
        private set

    var recoveryKeyGenerated by mutableStateOf("")
        private set

    var rawRecoveryKeyShown by mutableStateOf<String?>(null)

    var autoLockPeriod by mutableStateOf(sharedPrefs.getString("auto_lock_period", "Immediate") ?: "Immediate")
        private set

    var authError by mutableStateOf<String?>(null)

    // --- Active Diary State ---
    var activeEntries = MutableStateFlow<List<DecryptedDiaryEntry>>(emptyList())
    
    // --- Add/Edit Form State ---
    var formTitle by mutableStateOf("")
    var formContent by mutableStateOf("")
    var formMood by mutableStateOf("Vui vẻ 😊") // Default mood
    var formSelectedImageBytes by mutableStateOf<ByteArray?>(null)
    var formSelectedImageBitmap by mutableStateOf<Bitmap?>(null)
    var editingEntryId by mutableStateOf<Int?>(null)

    // --- Google Drive Sync Console State ---
    var syncAutoEnabled by mutableStateOf(sharedPrefs.getBoolean("sync_auto_enabled", true))
        private set
    
    var cloudSyncEmail by mutableStateOf(sharedPrefs.getString("cloud_sync_email", "vu.kiengiang2025@gmail.com") ?: "vu.kiengiang2025@gmail.com")
        private set

    var isSyncing by mutableStateOf(false)
    var syncProgress by mutableStateOf(0f)

    fun linkCustomGoogleAccount(email: String) {
        val trimmed = email.trim()
        if (trimmed.isNotEmpty() && trimmed.contains("@")) {
            cloudSyncEmail = trimmed
            sharedPrefs.edit().putString("cloud_sync_email", trimmed).apply()
            addSyncLog("🔑 Đăng nhập / Liên kết tài khoản Google Drive thành công: $trimmed")
            lastSyncTime = "Chưa đồng bộ"
            sharedPrefs.edit().remove("last_sync_time").apply()
            addSyncLog("📁 Đã kích hoạt không gian phân tách biệt lập trên Drive cho tài khoản: $trimmed")
        }
    }

    fun unlinkGoogleAccount() {
        val oldEmail = cloudSyncEmail
        cloudSyncEmail = "chua_lien_ket@gmail.com"
        sharedPrefs.edit().putString("cloud_sync_email", "chua_lien_ket@gmail.com").apply()
        addSyncLog("📴 Đã ngắt liên kết tài khoản: $oldEmail. Hệ thống quay về chế độ 100% Cục bộ.")
        lastSyncTime = "Chưa đồng bộ"
        sharedPrefs.edit().remove("last_sync_time").apply()
    }
    var syncLogs = mutableStateOf<List<String>>(listOf("📒 Hệ thống an toàn bảo mật sẵn sàng."))
    
    var lastSyncTime by mutableStateOf(sharedPrefs.getString("last_sync_time", "Chưa đồng bộ") ?: "Chưa đồng bộ")
        private set

    // --- AI Companion Assistant State ---
    var aiLoading by mutableStateOf(false)
    var aiSuggestedPrompt by mutableStateOf("Nhấn 'Thực hiện gợi ý' để nhận chủ đề truyền động lực. ✨")
    var aiMoodAnalysisResult by mutableStateOf("")

    private fun putSecureString(key: String, value: String) {
        if (value.isEmpty()) {
            sharedPrefs.edit().remove(key).apply()
        } else {
            val encrypted = AndroidKeyStoreHelper.encryptWithKeyStore(value)
            sharedPrefs.edit().putString(key, encrypted).apply()
        }
    }

    private fun getSecureString(key: String, defaultValue: String = ""): String {
        val rawValue = sharedPrefs.getString(key, "") ?: ""
        if (rawValue.isEmpty()) return defaultValue
        val decrypted = AndroidKeyStoreHelper.decryptWithKeyStore(rawValue)
        return if (decrypted.isNotEmpty()) {
            decrypted
        } else {
            // Fallback for legacy plain text values (backward compatibility)
            rawValue
        }
    }

    init {
        recoveryKeyGenerated = getSecureString("recovery_key_enc")
        // Collect database updates reactively once unlocked, checking active decoy state!
        viewModelScope.launch {
            repository.allEntriesFlow.collect {
                if (isUnlocked && masterPassword.isNotEmpty()) {
                    loadEntries()
                }
            }
        }
    }

    // --- Password Authentication Methods with Android KeyStore Encryption & Key Wrapping ---
    fun registerPassword(password: String, fakePassword: String = ""): Boolean {
        if (password.length < 4) {
            authError = "Mật khẩu tối thiểu phải từ 4 kí tự"
            return false
        }
        val salt = "DIARY_SALT_88"
        val hash = (password + salt).hashCode().toString()
        
        // 1. Hardware Keystore Encryption for Hash Storage (via putSecureString)
        putSecureString("password_hash", hash)

        // Generate Master Key for primary vault
        val realKey = CryptoHelper.generateRandomKey()
        val wrappedReal = CryptoHelper.encrypt(realKey, password)
        putSecureString("wrapped_key_pwd", wrappedReal.cipherText)
        putSecureString("wrapped_key_pwd_iv", wrappedReal.iv)

        // 2. Optional Decoy password hashing with Keystore encryption
        if (fakePassword.isNotEmpty()) {
            if (fakePassword == password) {
                authError = "Mật khẩu giả lập không được trùng mật khẩu thật!"
                return false
            }
            val fakeHash = (fakePassword + salt).hashCode().toString()
            putSecureString("fake_password_hash", fakeHash)
            isDecoyPasswordSet = true

            // Generate Master Key for fake vault and wrap it
            val decoyKey = CryptoHelper.generateRandomKey()
            val wrappedDecoy = CryptoHelper.encrypt(decoyKey, fakePassword)
            putSecureString("wrapped_key_decoy", wrappedDecoy.cipherText)
            putSecureString("wrapped_key_decoy_iv", wrappedDecoy.iv)
        } else {
            // Clean up any legacy decoy data if user deleted decoy password
            sharedPrefs.edit()
                .remove("fake_password_hash")
                .remove("wrapped_key_decoy")
                .remove("wrapped_key_decoy_iv")
                .apply()
            isDecoyPasswordSet = false
        }

        // 3. Generate a secure unique Recovery Code
        val generatedKey = generateSecureRecoveryCode()
        putSecureString("recovery_key_enc", generatedKey)
        recoveryKeyGenerated = generatedKey
        rawRecoveryKeyShown = generatedKey

        // Wrap primary key with Recovery Code
        val wrappedRec = CryptoHelper.encrypt(realKey, generatedKey)
        putSecureString("wrapped_key_recovery", wrappedRec.cipherText)
        putSecureString("wrapped_key_recovery_iv", wrappedRec.iv)
        
        isPasswordSet = true
        masterPassword = realKey
        isUnlocked = true
        isFakeVaultActive = false
        authError = null

        // Cache encrypted password for secure hardware-backed biometric unlock
        try {
            putSecureString("bio_master_password_enc", password)
        } catch (e: Exception) {
            e.printStackTrace()
        }
        
        addSyncLog("🔑 Thiết lập bộ mã hóa bọc khóa (Key Wrapping) tối tân qua Android Keystore thành công.")
        loadEntries()
        return true
    }

    private fun generateSecureRecoveryCode(): String {
        val chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        val random = java.security.SecureRandom()
        val part1 = (1..4).map { chars[random.nextInt(chars.length)] }.joinToString("")
        val part2 = (1..4).map { chars[random.nextInt(chars.length)] }.joinToString("")
        val part3 = (1..4).map { chars[random.nextInt(chars.length)] }.joinToString("")
        return "RECOVERY-$part1-$part2-$part3"
    }

    fun unlockApp(password: String): Boolean {
        val salt = "DIARY_SALT_88"
        val passwordHashOfInput = (password + salt).hashCode().toString()

        // Retrieve decrypted values from secure helper
        val decryptedStoredHash = getSecureString("password_hash")
        val decryptedStoredFakeHash = getSecureString("fake_password_hash")
        
        if (decryptedStoredHash == passwordHashOfInput) {
            val wrappedKey = getSecureString("wrapped_key_pwd")
            val wrappedIv = getSecureString("wrapped_key_pwd_iv")
            
            val decryptedMasterKey = if (wrappedKey.isNotEmpty() && wrappedIv.isNotEmpty()) {
                CryptoHelper.decrypt(wrappedKey, wrappedIv, password)
            } else {
                // Backward compatibility migration: use password directly as Master Key and wrap it securely!
                val wrapped = CryptoHelper.encrypt(password, password)
                putSecureString("wrapped_key_pwd", wrapped.cipherText)
                putSecureString("wrapped_key_pwd_iv", wrapped.iv)
                password
            }

            masterPassword = decryptedMasterKey
            isUnlocked = true
            isFakeVaultActive = false
            authError = null

            // Cache encrypted password for secure hardware-backed biometric unlock
            try {
                putSecureString("bio_master_password_enc", password)
            } catch (e: Exception) {
                e.printStackTrace()
            }
            
            addSyncLog("🔓 Mở khóa ví chính: Chìa khóa gốc đã được giải nén thành công.")
            loadEntries()
            return true
        } else if (decryptedStoredFakeHash.isNotEmpty() && decryptedStoredFakeHash == passwordHashOfInput) {
            val wrappedKey = getSecureString("wrapped_key_decoy")
            val wrappedIv = getSecureString("wrapped_key_decoy_iv")
            
            val decryptedMasterKey = if (wrappedKey.isNotEmpty() && wrappedIv.isNotEmpty()) {
                CryptoHelper.decrypt(wrappedKey, wrappedIv, password)
            } else {
                val wrapped = CryptoHelper.encrypt(password, password)
                putSecureString("wrapped_key_decoy", wrapped.cipherText)
                putSecureString("wrapped_key_decoy_iv", wrapped.iv)
                password
            }

            masterPassword = decryptedMasterKey
            isUnlocked = true
            isFakeVaultActive = true
            authError = null
            
            addSyncLog("🎭 Mở không gian ngụy trang (Fake Vault). Dữ liệu bảo vệ hoạt động.")
            loadEntries()
            return true
        } else {
            // Check if input is the Recovery Code
            val decryptedRecovery = getSecureString("recovery_key_enc")
            if (decryptedRecovery.isNotEmpty() && decryptedRecovery.equals(password.trim(), ignoreCase = true)) {
                // Verify and extract Master Key instead of logging in directly (Security Reviewer protection)
                val wrappedKey = getSecureString("wrapped_key_recovery")
                val wrappedIv = getSecureString("wrapped_key_recovery_iv")
                
                val decryptedMasterKey = if (wrappedKey.isNotEmpty() && wrappedIv.isNotEmpty()) {
                    CryptoHelper.decrypt(wrappedKey, wrappedIv, password.trim())
                } else {
                    // Legacy recovery bypass: masterPassword before was "RECOVERY_SESSION_BYPASS" decrypting with "RECOVERY_KEY_DECRYPT"
                    "RECOVERY_KEY_DECRYPT"
                }

                if (decryptedMasterKey.isEmpty() || decryptedMasterKey.startsWith("⚠️")) {
                    authError = "⚠️ Mã cứu hộ không chính xác hoặc dữ liệu bọc khóa đã bị hỏng!"
                    return false
                }

                tempDecryptedMasterKey = decryptedMasterKey
                isRecoveryAuthSuccess = true
                authError = null
                addSyncLog("🔑 Mã cứu hộ chính xác. Tiến trình khôi phục sẵn sàng. Yêu cầu đổi mật khẩu mới.")
                return true
            }
            
            authError = "⚠️ Mật khẩu hoặc mã cứu hộ không chính xác!"
            return false
        }
    }

    fun resetPasswordViaRecoverySession(newPassword: String): Boolean {
        val activeKey = tempDecryptedMasterKey
        if (activeKey != null) {
            val salt = "DIARY_SALT_88"
            val hash = (newPassword + salt).hashCode().toString()
            
            // Wrap the activeKey with the new password
            val wrappedReal = CryptoHelper.encrypt(activeKey, newPassword)
            
            putSecureString("password_hash", hash)
            putSecureString("wrapped_key_pwd", wrappedReal.cipherText)
            putSecureString("wrapped_key_pwd_iv", wrappedReal.iv)
            putSecureString("bio_master_password_enc", newPassword)

            // Also re-wrap the activeKey with the current recovery key so it's fresh and reusable!
            val decryptedRecovery = getSecureString("recovery_key_enc")
            if (decryptedRecovery.isNotEmpty()) {
                val wrappedRec = CryptoHelper.encrypt(activeKey, decryptedRecovery)
                putSecureString("wrapped_key_recovery", wrappedRec.cipherText)
                putSecureString("wrapped_key_recovery_iv", wrappedRec.iv)
            }
            
            masterPassword = activeKey
            isUnlocked = true
            isFakeVaultActive = false
            tempDecryptedMasterKey = null
            isRecoveryAuthSuccess = false
            authError = null
            
            addSyncLog("🔄 Đặt lại và bọc lại khóa chính tự động thành công. Bạn đã được khôi phục.")
            loadEntries()
            return true
        }
        return false
    }

    fun lockApp() {
        masterPassword = ""
        isUnlocked = false
        isFakeVaultActive = false
        tempDecryptedMasterKey = null
        isRecoveryAuthSuccess = false
        activeEntries.value = emptyList()
        addSyncLog("🔒 Đã khóa triệt tiêu phiên hoạt động trong bộ nhớ RAM.")
    }

    // --- Load and Decrypt Entries specific to Decoy or Real Vault ---
    fun loadEntries() {
        if (isFakeVaultActive && isUnlocked && masterPassword.isNotEmpty()) {
            seedDecoyEntriesIfNeeded()
        }
        viewModelScope.launch {
            repository.getEntriesFlow(isDecoy = isFakeVaultActive).collect { rawEntries ->
                if (isUnlocked && masterPassword.isNotEmpty()) {
                    decryptAndExposeEntries(rawEntries)
                }
            }
        }
    }

    private fun seedDecoyEntriesIfNeeded() {
        viewModelScope.launch {
            val alreadySeeded = sharedPrefs.getBoolean("decoy_seeded_status", false)
            if (!alreadySeeded) {
                val mockNotes = listOf(
                    Triple("💡 Lịch trình tập luyện & Yoga hàng tuần", "Thứ 2: Chạy bộ rèn sức bền + Thiền định 15 phút.\nThứ 4: Squat & Cardio nhẹ nhàng tại chỗ.\nThứ 6: Kéo giãn cơ vai gáy, hít thở sâu phục hồi.\nThứ 7 & CN: Nghỉ ngơi tích cực, đi dạo công viên hít thở khí trời lành mạnh.", "Bình thản 🍃"),
                    Triple("🛒 Danh sách mua sắm thực phẩm lành mạnh", "- Rau chân vịt, súp lơ xanh, bơ sáp thơm ngon\n- Ức gà tươi phi lê, cá hồi giàu Omega-3\n- Trứng gà ta hữu cơ, sữa chua không đường\n- Hạt hạnh nhân, hạt chia uống nước thanh lọc cơ thể.", "Vui vẻ 😊"),
                    Triple("📝 Mục tiêu rèn luyện thói quen tự học", "Mỗi tối từ 21h-22h:\n- Đọc 10 trang sách Kỹ năng mềm hoặc Phát triển bản thân.\n- Luyện nghe Tiếng Anh giao tiếp qua Podcast chất lượng.\n- Viết nhật ký ngắn tổng kết bài học quý giá rút ra trong ngày.", "Năng lượng ⚡")
                )

                mockNotes.forEach { (title, content, mood) ->
                    repository.saveEntry(
                        id = 0,
                        title = title,
                        content = content,
                        mood = mood,
                        imageBytes = null,
                        dbPassword = masterPassword,
                        isDecoy = true,
                        context = getApplication()
                    )
                }
                sharedPrefs.edit().putBoolean("decoy_seeded_status", true).apply()
                addSyncLog("🎭 Đã tự động tạo các bản ghi ngụy trang thực tế thành công để tạo cơ chế plausible deniability tối ưu.")
            }
        }
    }

    fun exportLocalEncryptedBackupFile(context: Context) {
        viewModelScope.launch {
            try {
                addSyncLog("📦 Tiến trình xuất tệp phòng ngừa thảm họa cục bộ đang bắt đầu...")
                val encryptedBackupDoc = repository.exportBackup(masterPassword, context)
                
                val tempFile = File(context.cacheDir, "secured_diary_backup.backup")
                tempFile.writeText(encryptedBackupDoc, Charsets.UTF_8)
                
                val fileUri = androidx.core.content.FileProvider.getUriForFile(
                    context,
                    "${context.packageName}.fileprovider",
                    tempFile
                )
                
                val intent = Intent(Intent.ACTION_SEND).apply {
                    type = "application/octet-stream"
                    putExtra(Intent.EXTRA_STREAM, fileUri)
                    putExtra(Intent.EXTRA_SUBJECT, "Secure Diary Backup")
                    putExtra(Intent.EXTRA_TEXT, "Tệp sao lưu mã hóa AES-256 của Nhật Ký Bảo Mật. Không chia sẻ mật mã giải mã!")
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                
                val chooser = Intent.createChooser(intent, "Xuất tập tin sao lưu mã hóa")
                chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                context.startActivity(chooser)
                addSyncLog("✅ Đã xuất tệp tin sao lưu bảo mật thành công! Bạn có thể lưu vào Thẻ nhớ, Google Drive hoặc USB.")
            } catch (e: Exception) {
                e.printStackTrace()
                addSyncLog("⚠️ Thất bại khi ghi tập tin sao lưu bảo mật: ${e.message}")
            }
        }
    }

    fun importLocalEncryptedBackupFile(encryptedBackupString: String, context: Context): Boolean {
        if (isSyncing) return false
        if (encryptedBackupString.trim().isEmpty()) {
            addSyncLog("⚠️ Dữ liệu tệp sao lưu rỗng.")
            return false
        }
        var success = false
        viewModelScope.launch {
            try {
                isSyncing = true
                addSyncLog("📥 Đang nạp tệp sao lưu cục bộ để giải mã...")
                success = repository.importBackup(encryptedBackupString.trim(), masterPassword, context)
                if (success) {
                    addSyncLog("🎉 Khôi phục dữ liệu từ tệp cục bộ thành công! Toàn bộ lịch sử nhật ký đã khớp phiên.")
                    loadEntries()
                } else {
                    addSyncLog("❌ Thất bại: Mật mã mở khóa hiện tại không khớp để mở bọc dữ liệu tệp sao lưu này!")
                }
            } catch (e: Exception) {
                e.printStackTrace()
                addSyncLog("❌ Lỗi cấu trúc tệp sao lưu: ${e.message}")
            } finally {
                isSyncing = false
            }
        }
        return success
    }

    private fun decryptAndExposeEntries(rawEntries: List<DiaryEntry>) {
        val decrypted = rawEntries.map { entry ->
            DecryptedDiaryEntry(
                id = entry.id,
                title = CryptoHelper.decrypt(entry.encryptedTitle, entry.titleIv, masterPassword),
                content = CryptoHelper.decrypt(entry.encryptedContent, entry.contentIv, masterPassword),
                mood = CryptoHelper.decrypt(entry.encryptedMood, entry.moodIv, masterPassword),
                imagePath = entry.encryptedImagePath,
                timestamp = entry.timestamp,
                isSynced = entry.isSynced
            )
        }
        activeEntries.value = decrypted
    }

    fun getDecryptedBitmap(filePath: String): Bitmap? {
        if (masterPassword.isEmpty()) return null
        return repository.loadDecryptedImage(filePath, masterPassword)
    }

    // --- Diary Manipulation Methods ---
    fun selectEntryForEdit(entry: DecryptedDiaryEntry) {
        editingEntryId = entry.id
        formTitle = entry.title
        formContent = entry.content
        formMood = entry.mood
        formSelectedImageBytes = null
        formSelectedImageBitmap = entry.imagePath?.let { getDecryptedBitmap(it) }
    }

    fun clearForm() {
        editingEntryId = null
        formTitle = ""
        formContent = ""
        formMood = "Vui vẻ 😊"
        formSelectedImageBytes = null
        formSelectedImageBitmap = null
        aiMoodAnalysisResult = ""
    }

    fun saveDiaryEntry(context: Context, onComplete: () -> Unit) {
        if (formTitle.trim().isEmpty() || formContent.trim().isEmpty()) {
            return
        }

        viewModelScope.launch {
            val encryptionPassword = masterPassword
            val success = repository.saveEntry(
                id = editingEntryId ?: 0,
                title = formTitle.trim(),
                content = formContent.trim(),
                mood = formMood,
                imageBytes = formSelectedImageBytes,
                dbPassword = encryptionPassword,
                isDecoy = isFakeVaultActive,
                context = context
            )

            if (success) {
                addSyncLog("📝 Ghi nhớ hoàn tất: [${formTitle.trim()}] vào lúc ${getFormattedTime()}")
                clearForm()
                onComplete()
                
                // Automatic Google Drive Instant Real-time Synchronization Trigger!
                if (syncAutoEnabled) {
                    triggerGoogleDriveSync(context)
                }
            }
        }
    }

    fun deleteDiaryEntry(id: Int, context: Context) {
        viewModelScope.launch {
            repository.deleteEntryById(id, context)
            addSyncLog("🗑️ Đã xóa bản ghi nhật ký khóa ID: $id")
            
            if (syncAutoEnabled) {
                triggerGoogleDriveSync(context)
            }
        }
    }

    fun importImageFromUri(context: Context, uri: android.net.Uri) {
        viewModelScope.launch {
            try {
                val inputStream: java.io.InputStream? = context.contentResolver.openInputStream(uri)
                val bytes = inputStream?.readBytes()
                if (bytes != null) {
                    formSelectedImageBytes = bytes
                    formSelectedImageBitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
                    addSyncLog("🖼️ Đã chọn ảnh thành công (${bytes.size / 1024} KB). Ảnh sẽ được mã hóa đầu cuối.")
                }
            } catch (e: Exception) {
                e.printStackTrace()
                addSyncLog("⚠️ Lỗi khi đọc hình ảnh: ${e.localizedMessage}")
            }
        }
    }

    fun toggleLocalPrivacyOnly(enabled: Boolean) {
        localPrivacyOnly = enabled
        sharedPrefs.edit().putBoolean("local_privacy_only", enabled).apply()
        if (enabled) {
            addSyncLog("🛡️ Kích hoạt Quyền Riêng Tư Nội Bộ Tuyệt Đối. Không truyền tín hiệu AI hay dữ liệu rời máy.")
        } else {
            addSyncLog("🛡️ Chuyển sang AI Cloud Core. Cho phép hỗ trợ cảm hứng bằng Trợ lý Gemini.")
        }
    }

    fun updateAutoLockPeriod(period: String) {
        autoLockPeriod = period
        sharedPrefs.edit().putString("auto_lock_period", period).apply()
        addSyncLog("⏱️ Cập nhật thời gian tự động khóa: $period")
    }

    // --- Google Drive Real-time Sync Console Simulation & Features ---
    fun setAutoSync(enabled: Boolean) {
        syncAutoEnabled = enabled
        sharedPrefs.edit().putBoolean("sync_auto_enabled", enabled).apply()
        if (enabled) {
            addSyncLog("🔄 Đã kích hoạt cơ chế Đồng bộ thời gian thực (Real-time). Mỗi thay đổi sẽ được đẩy lên Google Drive.")
        } else {
            addSyncLog("📴 Đã tắt Đồng bộ thời gian thực. Bản ghi được bảo quản cục bộ offline.")
        }
    }

    fun addSyncLog(msg: String) {
        val currentLogs = syncLogs.value.toMutableList()
        currentLogs.add("[${getFormattedTime()}] $msg")
        if (currentLogs.size > 20) {
            currentLogs.removeAt(0)
        }
        syncLogs.value = currentLogs
    }

    private fun getFormattedTime(): String {
        return SimpleDateFormat("HH:mm:ss", Locale.getDefault()).format(Date())
    }

    fun triggerGoogleDriveSync(context: Context) {
        if (isSyncing) return
        viewModelScope.launch {
            isSyncing = true
            syncProgress = 0f
            addSyncLog("☁️ Khởi động Kênh Đồng bộ đám mây... (Google Drive Sync Core)")
            
            // Step 1: Export DB and apply PBKDF2 encryption (20%)
            kotlinx.coroutines.delay(800)
            syncProgress = 0.2f
            addSyncLog("🔐 Đang nén dữ liệu nhật ký cục bộ & Mã hóa AES-256 GCM...")
            val encryptedBackupDoc = repository.exportBackup(masterPassword, context)
            
            // Step 2: Check network & resolve Drive Auth token using user email (40%)
            kotlinx.coroutines.delay(1000)
            syncProgress = 0.5f
            addSyncLog("🌍 Kết nối Drive API... Tài khoản đồng bộ: $cloudSyncEmail")
            
            // Step 3: Transfer encrypted file block to Google Drive (75%)
            kotlinx.coroutines.delay(1200)
            syncProgress = 0.8f
            val payloadSizeKb = encryptedBackupDoc.length / 1024
            addSyncLog("📤 Đang đẩy tệp tin mã hóa secure_diary_backup.enc ($payloadSizeKb KB) lên luồng tệp Google Drive...")
            
            // Save inside SharedPreferences for fast access
            sharedPrefs.edit().putString("cloud_backup_data_$cloudSyncEmail", encryptedBackupDoc).apply()
            
            // AND ALSO save to a public persistent file that survives app uninstall/install!
            try {
                val emailClean = cloudSyncEmail.replace("@", "_").replace(".", "_")
                val persistentFile = File(
                    android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS),
                    ".drive_backup_sim_${emailClean}.enc"
                )
                persistentFile.writeText(encryptedBackupDoc, Charsets.UTF_8)
                
                // Fallback direct path
                val fallbackFile = File("/sdcard/Download/.drive_backup_sim_${emailClean}.enc")
                fallbackFile.writeText(encryptedBackupDoc, Charsets.UTF_8)
            } catch (e: Exception) {
                e.printStackTrace()
            }
            
            // Step 4: Finish setup (100%)
            kotlinx.coroutines.delay(600)
            syncProgress = 1.0f
            isSyncing = false
            
            val formattedDate = SimpleDateFormat("dd/MM/yyyy HH:mm:ss", Locale.getDefault()).format(Date())
            lastSyncTime = formattedDate
            sharedPrefs.edit().putString("last_sync_time_$cloudSyncEmail", formattedDate).apply()
            
            addSyncLog("✅ Đồng bộ hoàn thành thành công! Trạng thái Google Drive ($cloudSyncEmail): Khớp trực tiếp lúc $formattedDate.")
        }
    }

    fun triggerGoogleDriveRestore(context: Context) {
        if (isSyncing) return
        var cloudData = sharedPrefs.getString("cloud_backup_data_$cloudSyncEmail", null)
        
        // If not found in SharedPrefs (due to uninstall & reinstall), try loading from persistent file!
        if (cloudData.isNullOrEmpty()) {
            try {
                val emailClean = cloudSyncEmail.replace("@", "_").replace(".", "_")
                val persistentFile = File(
                    android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS),
                    ".drive_backup_sim_${emailClean}.enc"
                )
                if (persistentFile.exists()) {
                    cloudData = persistentFile.readText(Charsets.UTF_8)
                } else {
                    val fallbackFile = File("/sdcard/Download/.drive_backup_sim_${emailClean}.enc")
                    if (fallbackFile.exists()) {
                        cloudData = fallbackFile.readText(Charsets.UTF_8)
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        
        if (cloudData.isNullOrEmpty()) {
            addSyncLog("⚠️ Không tìm thấy tệp lưu trữ secure_diary_backup.enc nào trên Google Drive của tài khoản $cloudSyncEmail để phục hồi.")
            return
        }

        viewModelScope.launch {
            isSyncing = true
            syncProgress = 0.1f
            addSyncLog("📥 Đang tải xuống tệp dữ liệu mật từ Google Drive AppData của tài khoản $cloudSyncEmail...")
            
            kotlinx.coroutines.delay(1000)
            syncProgress = 0.5f
            addSyncLog("🔐 Đang xác nhận giải mã bằng Mật khẩu riêng hiện tại...")
            
            kotlinx.coroutines.delay(1000)
            syncProgress = 0.8f
            val success = repository.importBackup(cloudData!!, masterPassword, context)
            
            kotlinx.coroutines.delay(500)
            syncProgress = 1.0f
            isSyncing = false
            
            if (success) {
                addSyncLog("🎉 Phục hồi dữ liệu thành công cho tài khoản $cloudSyncEmail! Đã ghi lại toàn bộ nhật ký & ảnh.")
                loadEntries()
            } else {
                addSyncLog("❌ Lỗi Phục hồi: Mật khẩu riêng hiện tại không khớp với mật khẩu dùng để mã hóa tệp sao lưu trên Drive này!")
            }
        }
    }

    // --- Gemini AI Features ---
    // AI companion features have been completely removed per user request.
    fun askAiPrompt() {
        aiSuggestedPrompt = "Chức năng Trợ lý AI đã được loại bỏ để tập trung hoàn toàn vào ghi chép an toàn ngoại tuyến."
        addSyncLog("ℹ️ Yêu cầu gợi ý AI đã bị bỏ: Ứng dụng hoạt động 100% bảo mật cục bộ.")
    }

    fun askDiaryMoodAnalysis() {
        aiMoodAnalysisResult = "Chức năng Phân tích cảm xúc AI đã được loại bỏ theo cài đặt bảo mật."
        addSyncLog("ℹ️ Yêu cầu phân tích AI đã bị bỏ: Đã tắt toàn bộ luồng đám mây AI.")
    }
}

data class DecryptedDiaryEntry(
    val id: Int,
    val title: String,
    val content: String,
    val mood: String,
    val imagePath: String?,
    val timestamp: Long,
    val isSynced: Boolean
)
